#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "config.h"
#include "terminal.h"
#include "gdt.h"
#include "idt.h"
#include "defines.h"
#include "isr.h"
#include "keyboard.h"
#include "multitasking.h"
#include "pic.h"
#include "pmm.h"
#include "cmos.h"