#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdarg.h>
#include "include/console.h"
#include "include/elf.h"
#include "include/intr.h"
#include "include/mm.h"
#include "include/multiboot.h"
#include "include/string.h"
#include "include/keyboard.h"
#include "include/modes.h"
#include "include/vga.h"
#include "include/tasks.h"
#include "include/math.h"
#include "include/sound.h"
#include "include/cmos.h"
#include "include/timer.h"
#include "include/pci.h"
#include "include/via.h"
#include "network/include/declerations.h"
