#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdarg.h>
#include "console.h"
#include "elf.h"
#include "intr.h"
#include "mm.h"
#include "multiboot.h"
#include "string.h"
#include "keyboard.h"
#include "modes.h"
#include "vga.h"
#include "tasks.h"
#include "math.h"
#include "sound.h"
#include "cmos.h"
#include "timer.h"
#include "pci.h"
#include "via.h"
#include "declerations.h"
#include "dhcp.h"
